# This is a basic workflow to help you get started with Actions

name: Build DB

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 3' # Every wednesday

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install sqlite3

      - name: Run DB import script and compress result
        run: |
          bash bs4dumpvdl2.sh
          XZ_OPT=-9 tar cJf BaseStation.sqb.tar.xz BaseStation.sqb
          tar czf BaseStation.sqb.tar.gz BaseStation.sqb
      
      - name: 'Upload Artifact BaseStation.sqb.tar.xz'
        uses: actions/upload-artifact@v3
        with:
          name: BaseStation.sqb.tar.xz
          path: BaseStation.sqb.tar.xz
          retention-days: 10

      - name: 'Upload Artifact BaseStation.sqb.tar.xz'
        uses: actions/upload-artifact@v3
        with:
          name: BaseStation.sqb.tar.gz
          path: BaseStation.sqb.tar.gz
          retention-days: 10
  
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Autobuild"
          files: |
            BaseStation.sqb.tar.xz
            BaseStation.sqb.tar.gz
  
